version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "ğŸ¤– Dependencies"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/server"
    labels:
      - "ğŸ¤– Dependencies"
    schedule:
      interval: "daily"